### ISSUE TITLE
jr: Loading界面应该只覆盖在图片容器上

### ISSUE THREAD

**Issue by ekkure** [no-tomatoes-tonight-or-id-scream/image-restorer-frontend#10]
目前的Loading界面是全屏模糊，我认为调整的方法有两种
1. 将全屏模糊去掉，只保留Loading动态图标，这种方法比较简单
2. 按jr所说，一种方法将Loading移到ImageComparison组件中，因为这个组件直接和图片打交道，如果还在Menu中的话还需要组件通信，且这个组件掌握图片加载完成的时机，可以很简单的将 #5 解决，总体来说可以减少任务复杂度

我偏向第一种 (

**Comment by Ngaizean** [comment]
这个我也想过 但是覆盖图片会好点 因为如果不覆盖 只是一个图片 图片就是闪的一下处理好

覆盖图片的话 没那么生硬

这个Menu和图片组件的通信应该比较简单 我来看看吧
