### ISSUE TITLE
Loading页面消失的时机

### ISSUE THREAD

**Issue by ekkure** [no-tomatoes-tonight-or-id-scream/image-restorer-frontend#5]
```js
 if (status === "completed") {
     this.getResultImg(task_id);
     setTimeout(() => {
         this.isLoading = false; // 加载完成后隐藏
     }, 1500);
}
```
现在Loading界面的消失是固定的当查询到任务状态为`completed`后1.5s，可以适当作统一调整（2s），或者与其他组件（图像显示的组件）沟通调整时机。两种方法都可以

**Comment by Ngaizean** [comment]
我发现这个Loading页面完成后，有时过一会我的对比滑块组件才会出来，有时间差。或许在我的对比组件那里设置一个信号，一旦我的组件加载好了我把信号回传给你，你再把loading关掉会更好
