### ISSUE TITLE
get_result 报错 loading 不消失

### ISSUE THREAD

**Issue by hongjr03** [no-tomatoes-tonight-or-id-scream/image-restorer-frontend#6]
![image](https://github.com/user-attachments/assets/7a030f9d-1c9c-4b5a-a9a9-a08d2f160565)

**Comment by ekkure** [comment]
出错的get_result之前进行了多少次的get_status

**Comment by hongjr03** [comment]
跟这个没关系吧，这不该是错误处理的范畴？

**Comment by Ngaizean** [comment]
出错就搞个出错提示吧

**Comment by ekkure** [comment]
现在get_result一个是等completed，另一个是尝试的次数过多了直接去get_result的，如果是在第二种出错的话第二个分支加上关闭就好了

**Comment by ekkure** [comment]
这个 commit可能 解决了这个问题: [ea4dc2e38d32e747978ff29d6d3be6820de479f6](https://github.com/no-tomatoes-tonight-or-id-scream/image-restorer-frontend/commit/ea4dc2e38d32e747978ff29d6d3be6820de479f6)
