### ISSUE TITLE
处理后页面逻辑

### ISSUE THREAD

**Issue by hongjr03** [no-tomatoes-tonight-or-id-scream/image-restorer-frontend#7]
处理后按钮应变为下载图像和回到主界面
![image](https://github.com/user-attachments/assets/1d1b9f5c-b220-4f57-b4e2-ef44b3421207)

**Comment by Ngaizean** [comment]
看看能不能做按钮一分为二的动效（）
anyway 那个tailwind有提供下载按钮的动画 那个拿过来好像不错https://tailwindcss.com/docs/animation

**Comment by Ngaizean** [comment]
我路由跳转完成了 @ekkure
